### ISSUE TITLE
Add: Practical tutorials for all technologies and tools

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/awesome-coding-and-designing#15]
- Beginners have no idea why and how they should choose a tool.
- This collection does only list tools.
- There are no practical tutorials here yet.
- So the value for beginners is limited.

**Comment by LBeul** [comment]
Maybe it would be easier to split this in half. The README could link to other .md files: toolBox.md and tutorials.md. That would make it easier for newbies to distinguish between tools & tutorials as well as improve the whole structure of the site.
